title: CSE 15L Lab Reports
author: Isaiah Jones
  #name: GitHub User
  #email: ijjones@ucsd.edu
description: > # this means to ignore newlines until "show_excerpts:"
  CSE 15L is a hands-on exploration of software development tools and techniques. Investigation of the scientific 
  process as applied to software development and debugging. Emphasis is on weekly hands-on laboratory 
  experiences, development of laboratory notebooking techniques as applied to software design.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  
header_pages:
  - about.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
